import type { Host, Runtime } from './runtime-types'

export const mockHosts: Host[] = [
  {
    id: 'host-macbook',
    name: 'adam-macbook',
    status: 'online',
    managed: false,
    tunnelStatus: 'connected',
    os: 'macOS 15.3',
    arch: 'arm64',
    capabilities: ['docker'],
    lastSeen: '2 minutes ago',
    registeredAt: '2 weeks ago',
  },
  {
    id: 'host-staging',
    name: 'staging-1',
    status: 'error',
    managed: false,
    tunnelStatus: 'disconnected',
    os: 'Ubuntu 24.04',
    arch: 'x86_64',
    capabilities: ['docker'],
    lastSeen: '2 hours ago',
    registeredAt: '1 week ago',
  },
  {
    id: 'host-gpu',
    name: 'gpu-rack-3',
    status: 'offline',
    managed: false,
    tunnelStatus: 'disconnected',
    os: 'Ubuntu 24.04',
    arch: 'x86_64',
    capabilities: ['docker', 'gpu:a100'],
    lastSeen: '1 day ago',
    registeredAt: '5 days ago',
  },
  {
    id: 'host-cloud',
    name: 'Stoneforge Cloud',
    status: 'online',
    managed: true,
    provider: 'stoneforge',
    region: 'us-east-1',
    defaultTier: 'medium',
    activeSandboxCount: 2,
    capabilities: ['sandbox', 'docker'],
    lastSeen: 'just now',
    registeredAt: '1 month ago',
  },
  {
    id: 'host-e2b',
    name: 'E2B',
    status: 'online',
    managed: true,
    provider: 'e2b',
    region: 'us-west-2',
    defaultTier: 'small',
    activeSandboxCount: 0,
    capabilities: ['sandbox'],
    lastSeen: 'just now',
    registeredAt: '2 weeks ago',
  },
  {
    id: 'host-modal',
    name: 'Modal',
    status: 'online',
    managed: true,
    provider: 'modal',
    region: 'us-east-1',
    defaultTier: 'medium',
    activeSandboxCount: 0,
    capabilities: ['sandbox', 'docker', 'gpu:a100'],
    lastSeen: 'just now',
    registeredAt: '1 week ago',
  },
  {
    id: 'host-fly',
    name: 'Fly.io',
    status: 'online',
    managed: true,
    provider: 'fly',
    region: 'iad',
    defaultTier: 'small',
    activeSandboxCount: 0,
    capabilities: ['docker'],
    lastSeen: 'just now',
    registeredAt: '3 days ago',
  },
  {
    id: 'host-daytona',
    name: 'Daytona',
    status: 'offline',
    managed: true,
    provider: 'daytona',
    region: 'eu-west-1',
    defaultTier: 'medium',
    activeSandboxCount: 0,
    capabilities: ['sandbox', 'docker'],
    lastSeen: '3 days ago',
    registeredAt: '1 week ago',
  },
]

export const mockRuntimes: Runtime[] = [
  {
    id: 'rt-local-1',
    name: 'adam-macbook',
    hostId: 'host-macbook',
    mode: 'worktrees',
    status: 'online',
    isDefault: true,
    createdAt: '2 weeks ago',
    lastHealthCheck: '2 minutes ago',
    worktreePath: '.stoneforge/worktrees',
    assignedAgentCount: 3,
    assignedAgentIds: ['a1', 'a4', 'a5'],
    cpu: 45,
    memory: '2.1 GB',
    disk: '12 GB free',
  },
  {
    id: 'rt-docker-1',
    name: 'docker-local',
    hostId: 'host-macbook',
    mode: 'docker',
    status: 'online',
    isDefault: false,
    createdAt: '3 days ago',
    lastHealthCheck: '5 minutes ago',
    dockerImage: 'ghcr.io/stoneforge/worker:latest',
    assignedAgentCount: 1,
    assignedAgentIds: ['a8'],
    cpu: 12,
    memory: '512 MB',
    disk: '4.2 GB free',
  },
  {
    id: 'rt-ssh-1',
    name: 'staging-worktree',
    hostId: 'host-staging',
    mode: 'worktrees',
    status: 'error',
    statusMessage: 'Tunnel disconnected 2h ago',
    isDefault: false,
    createdAt: '1 week ago',
    lastHealthCheck: '2 hours ago',
    worktreePath: '~/workspace/.stoneforge/worktrees',
    assignedAgentCount: 0,
    assignedAgentIds: [],
  },
  {
    id: 'rt-ssh-2',
    name: 'gpu-docker',
    hostId: 'host-gpu',
    mode: 'docker',
    status: 'offline',
    isDefault: false,
    createdAt: '5 days ago',
    lastHealthCheck: '1 day ago',
    dockerImage: 'ghcr.io/stoneforge/worker-gpu:latest',
    assignedAgentCount: 2,
    assignedAgentIds: ['a3', 'a7'],
  },
  {
    id: 'rt-sandbox-1',
    name: 'cloud-sandbox',
    hostId: 'host-cloud',
    mode: 'sandbox',
    status: 'online',
    isDefault: false,
    createdAt: '1 day ago',
    lastHealthCheck: 'just now',
    sandboxTier: 'medium',
    assignedAgentCount: 2,
    assignedAgentIds: ['a2', 'a6'],
  },
]
