name: Bug Report
description: Report a bug in Stoneforge
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: false
  - type: dropdown
    id: node-version
    attributes:
      label: Node version
      options:
        - "22"
        - "20"
        - "18"
        - Other
    validations:
      required: false
  - type: input
    id: package-version
    attributes:
      label: Package version
      placeholder: e.g. 1.0.0
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context, screenshots, or logs.
    validations:
      required: false
