name: Feature Request
description: Suggest a new feature for Stoneforge
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why do you need this feature? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered.
    validations:
      required: false
